<a href="https://colab.research.google.com/github/nuccio99/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Introduction to Tensors
Tensor: is a way to represent data

### Creating tensors
They are created with "torch.tensor()"

In [ ]:
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# Dimension: number of square brackets
vector.ndim


1

In [ ]:
# Size
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape
# this means that we have 1 3x3 matrix

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# More practice with tensors

### Create a tensor of size [1,2,1]


In [ ]:
tensor121=torch.tensor([[[1],
                         [2]]])
tensor121

tensor([[[1],
         [2]]])

In [ ]:
tensor121.ndim

3

In [ ]:
tensor121.shape

torch.Size([1, 2, 1])

### Create a matrix 4x2


In [ ]:
matrix42=torch.tensor([[1,1],[0,0],[2,2],[3,3]])
matrix42

tensor([[1, 1],
        [0, 0],
        [2, 2],
        [3, 3]])

In [ ]:
matrix42.ndim

2

In [ ]:
matrix42.shape

torch.Size([4, 2])

# Random tensors

Many neural networks learn based on initial tensors full of random numbers and then adjust those random numbers to better represent the patterns between data

In [ ]:
# Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0885, 0.7797, 0.4002, 0.3456],
        [0.0643, 0.3114, 0.2106, 0.6463],
        [0.9702, 0.7383, 0.1955, 0.7827]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor of size (2,2,2)
random_tensor2=torch.rand(2,2,2)
random_tensor2

tensor([[[0.9916, 0.9301],
         [0.7580, 0.4661]],

        [[0.3783, 0.1005],
         [0.8309, 0.6470]]])

In [ ]:
# Create a number tensor with a similar shape to an image tensor
random_image_size_tensor=torch.rand(3,224,224)
random_image_size_tensor.ndim,random_image_size_tensor.shape 

(3, torch.Size([3, 224, 224]))

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype 

torch.float32

### Create a range of tensors and tensors-like

In [ ]:
# Create a range
zero_to_ten=torch.arange(0,11)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
zero_to_ten.ndim

1

In [ ]:
# Other method with a step size
zero_to_ten=torch.arange(start=0,end=11,step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create tensors like : create a tensor with the shape equal to an other one
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors in PyTorch:

1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, #datatype
                             device=None,# what device is your tensor on
                             requires_grad=False) #whether or not to track gradients with the tensors operation


float_32_tensor


tensor([3., 6., 9.])

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

In [ ]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.3133, 0.2245, 0.7378, 0.9452],
        [0.4234, 0.8547, 0.1176, 0.5501],
        [0.7637, 0.0136, 0.7627, 0.1729]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3133, 0.2245, 0.7378, 0.9452],
        [0.4234, 0.8547, 0.1176, 0.5501],
        [0.7637, 0.0136, 0.7627, 0.1729]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication 
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions (in general use above command)
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
# Element wise multiplication
tensor*tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.matmul(tensor_A,tensor_B)


RuntimeError: ignored

In [ ]:
# Transpose of a tensor
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min,max,mean,sum,etc (Tensor aggregation)

In [ ]:
# Create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min(), x.max()

(tensor(0), tensor(90))

In [ ]:
x.mean()
x.dtype

RuntimeError: ignored

### To compute the mean, the floating 32 bit datatype is needed

In [ ]:
x.mean(dtype=torch.float32), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
x.sum()

tensor(450)

### Finding the positional min and max : use argmin() and argmax()



In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value
x.argmin()

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors along a dimension
* Squeeze - removes all "1" dimensions from a tensor
* Unsqueeze - add a "1" dimension to a target tensor
* Permute - Return a view of the input with dimension permuted in a certain way


In [ ]:
# Create a tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped=x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [ ]:
# Change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x], dim=1)
x_stacked
# Changing z changes x because a view of a tensor shares the same memory as the original one
z[0,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [113]:
# Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x], dim=1)
x_stacked# Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x], dim=1)


In [117]:
# Squeeze and Unsqueeze
x=torch.zeros(2,1,2,1,2)
x.shape

torch.Size([2, 1, 2, 1, 2])

In [118]:
y=torch.squeeze(x)
y.shape

torch.Size([2, 2, 2])

In [121]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [120]:
# Unsqueeze: add an extra dimension 
y_unsqueezed=y.unsqueeze(dim=0)
y_unsqueezed

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])

In [122]:
# Permute: rearranges the dimension of a target tensor in a specified order
x_original=torch.rand(224,224,3)

# permute the original tensor to rearrange the axis (or dim)
x_permuted=x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing (selecting data from tensors)


In [123]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [128]:
x[0,0,2]

tensor(3)

In [129]:
x[0,:,1]

tensor([2, 5, 8])

In [130]:
x[0,1,1]

tensor(5)

In [131]:
x[0,0,:]

tensor([1, 2, 3])

In [132]:
import torch


In [135]:
x=torch.tensor([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [145]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [146]:
# Index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

In [147]:
# Index on x to return 7,8,9
x[0,2,:]

tensor([7, 8, 9])

## PyTorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor 
* Pytorch tensor -> Numpy

In [151]:
# Numpy array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [152]:
tensor.dtype

torch.float64

### Numpy creates arrays with standard datatype float 64 bit, so when we convert from numpy to pytorch we create a tensor with datatype float 32 bit

In [153]:
# Change the value of array, what will this do to "tensor"?
array=array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [154]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [155]:
numpy_tensor.dtype

dtype('float32')

### Also NumPy reflects the standard datatype of PyTorch

## Reproducability

In short how a NN learns:
'start with random numbers -->  tensor operations --> update random numbers to make them better representations of data --> again --> again

To reduce the randomness in NN and PyTorch comes the concept of **random seed**. It "flavour" the randomness.

In [163]:
# Create two random tensors
random_tensor_A= torch.rand(3,4)
random_tensor_B= torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.2657, 0.3545, 0.6899, 0.9096],
        [0.7195, 0.6884, 0.5797, 0.9225],
        [0.0521, 0.7762, 0.0711, 0.3708]])
tensor([[0.7537, 0.6535, 0.8937, 0.2739],
        [0.1897, 0.7351, 0.3875, 0.4395],
        [0.9567, 0.1591, 0.2949, 0.3802]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [165]:
# Let's make some random but reproducible tensors
import torch
# set the random seed
RANDOM_SEED=42

torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors on the GPUs and making faster computation



In [2]:
!nvidia-smi

Fri Mar 10 15:17:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P0    27W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch


In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
#Count number of devices
torch.cuda.device_count()

1

## Putting tensors and models on the GPU



In [7]:
# Create a tensor (default on the CPU)

tensor = torch.tensor([1,2,3],device="cpu")
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# Move tensor to GPU if available
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [9]:
# If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [10]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_on_cpu=tensor_on_gpu.to("cpu").numpy()
tensor_on_cpu

array([1, 2, 3])